name: Docker Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            echo "📦 Pulling latest code"
            cd /home/winniio_admin/hospital-simulation-pipeline
            git pull origin main

            echo "🛑 Stopping previous containers"
            docker compose down

            echo "🔨 Rebuilding image"
            docker compose build

            echo "🚀 Starting new containers"
            docker compose up -d

            echo "🧼 Cleaning old dangling images"
            docker image prune -f
